version: '2.3'
services:
  buildkite:
    build:
      context: .
      dockerfile: buildkite-agent/Dockerfile
    volumes:
     - buildkite:/buildkite
     - ./buildkite-secrets:/buildkite/secrets:ro
     - ./buildkite-hooks:/buildkite/hooks:ro
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - BUILDKITE_AGENT_TOKEN
     - BUILDKITE_AGENT_NAME=${HOST}
     - BUILDKITE_AGENT_TAGS="queue=default,host=${HOST},docker=${DOCKER_VERSION},nvidia_docker=${NVIDIA_DOCKER_VERSION},nvidia_device=${NVIDIA_DEVICE}"
volumes:
  buildkite:
    external: True
