#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

set -x


BUILDKITE_HOST=`hostname -f`
DOCKER_VERSION=`docker version --format "{{.Server.Version}}"`
NVIDIA_DOCKER_VERSION=`nvidia-docker version | grep "NVIDIA Docker:" | sed -e "s/NVIDIA Docker: //"`

NVIDIA_DEVICE=$(
    set +e
    smi_result=`nvidia-smi --query-gpu=name -i 0 --format=csv,noheader`
    if [ $? -eq 0 ]; then
      echo ${smi_result}
    else
      echo ""
    fi
)

if [[ ! -z ${NVIDIA_DEVICE} ]]; then
  export BUILDKITE_QUEUE="cuda"
else
  export BUILDKITE_QUEUE="default"
fi
