#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

set -x

### Setup shared docker volume
docker volume create buildkite

### Load sekrats and environment information
source buildkite-secrets/docker-compose-env
source load-env

if [[ $BUILDKITE_QUEUE == "cuda" ]]; then
  docker-compose up --build "${@}" cuda_agent_0 cuda_agent_1
elif [[ $BUILDKITE_QUEUE == "default" ]]; then 
  docker-compose up --build "${@}" default_agent
fi
