#!/bin/bash
#http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -euo pipefail
IFS=$'\n\t'

set -x

### Setup shared docker volume
docker volume create buildkite

source buildkite-secrets/docker-compose-env
source load-env

docker-compose up --build $* buildkite
